/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menus;

import Tablas.ModelosTablas;
import Tablas.Tablas;
import static Menus.Global.id_trabajador;
import Tablas.Combos;
import static Tablas.Tablas.rellenaUsuariosGeneral;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author janillo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public static CardLayout cartaInicio= (CardLayout)new CardLayout();;
    public static CardLayout cartaMenus= (CardLayout)new CardLayout();;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {

        this.setAlwaysOnTop(true);

        initComponents();

        //Introducimos en los Layout los valores de los paneles
        //cartaInicio = (CardLayout)new CardLayout();
        cartaInicio.addLayoutComponent(pLogin, "pLogin");
        cartaInicio.addLayoutComponent(pApp, "pApp");
        pPrincipal.setLayout(cartaInicio);

        //cartaMenus = (CardLayout) new CardLayout();
        cartaMenus.addLayoutComponent(tpUsuarios, "tpUsuarios");
        cartaMenus.addLayoutComponent(tpArticulos, "tpArticulos");
        cartaMenus.addLayoutComponent(tpCompras, "tpCompras");
        cartaMenus.addLayoutComponent(tpVentas, "tpVentas");
        cartaMenus.addLayoutComponent(tpAjustes, "tpAjustes");
        
        pMenusillo.setLayout(cartaMenus);

        ModelosTablas.tablaConsultaGeneral();
        ModelosTablas.tablaUsuariosLogueo();
        ModelosTablas.tablaUsuariosTiendas();
Idiomas.Espanhol.cambiarAEspanhol();
    }

    public static void ocultar_inicio() {

        //CardLayout card = (CardLayout) pPrincipal.getLayout();
        //card.first(pPrincipal);
        cartaInicio.show(pPrincipal, "pLogin");

    }

    public static void mostrar_menus() {

        //cartaInicio = (CardLayout) pPrincipal.getLayout();
        cartaInicio.show(pPrincipal, "pApp");
        pMenusillo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pPrincipal = new javax.swing.JPanel();
        pLogin = new javax.swing.JPanel();
        pMiniLogin = new javax.swing.JPanel();
        bEntrar = new javax.swing.JButton();
        tfPass = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        pApp = new javax.swing.JPanel();
        lpUsuario = new javax.swing.JLayeredPane();
        etiqNA = new javax.swing.JLabel();
        etiqUsuario = new javax.swing.JLabel();
        bFrances = new javax.swing.JButton();
        bIngles = new javax.swing.JButton();
        bEspanhol = new javax.swing.JButton();
        lpMenus = new javax.swing.JLayeredPane();
        bMenuCompras = new javax.swing.JButton();
        bMenuVentas = new javax.swing.JButton();
        bMenuUsuarios = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bMenuArticulos = new javax.swing.JButton();
        bMenuClientes1 = new javax.swing.JButton();
        bMenuAjustes = new javax.swing.JButton();
        pMenusillo = new javax.swing.JPanel();
        tpCompras = new javax.swing.JTabbedPane();
        pRegistrarCompra = new javax.swing.JPanel();
        tpVentas = new javax.swing.JTabbedPane();
        pRegistrarVenta = new javax.swing.JPanel();
        tpAjustes = new javax.swing.JTabbedPane();
        pPreferencias = new javax.swing.JPanel();
        tpUsuarios = new javax.swing.JTabbedPane();
        pConsultaUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtGeneralUsuarios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUsuariosTiendas = new javax.swing.JTable();
        lTrabajadores = new javax.swing.JLabel();
        lTiendas = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtUsuariosAcceso = new javax.swing.JTable();
        lUsuarioAcceso = new javax.swing.JLabel();
        lUsuID = new javax.swing.JLabel();
        lUsuNombre = new javax.swing.JLabel();
        lUsuDNI = new javax.swing.JLabel();
        lUsuFecha = new javax.swing.JLabel();
        lUsuApe2 = new javax.swing.JLabel();
        lUsuDireccion = new javax.swing.JLabel();
        lUsuSexo = new javax.swing.JLabel();
        lUsuApe1 = new javax.swing.JLabel();
        lUsuTelefono = new javax.swing.JLabel();
        tfUsuID = new javax.swing.JTextField();
        tfUsuNombre = new javax.swing.JTextField();
        tfUsuApe1 = new javax.swing.JTextField();
        tfUsuApe2 = new javax.swing.JTextField();
        tfUsuDNI = new javax.swing.JTextField();
        tfUsuDireccion = new javax.swing.JTextField();
        tfUsuFecha = new javax.swing.JTextField();
        tfUsuSexo = new javax.swing.JTextField();
        tfUsuTelefono = new javax.swing.JTextField();
        lFoto = new javax.swing.JLabel();
        lFotoIMG = new javax.swing.JLabel();
        bUsuConsultar = new javax.swing.JButton();
        bUsuLimpiar = new javax.swing.JButton();
        bUsuActualizar = new javax.swing.JButton();
        pInsertaUsuarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPruebas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tpArticulos = new javax.swing.JTabbedPane();
        pConsultasArticulos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lArtReferencia = new javax.swing.JLabel();
        tfArtReferencia = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtArtVentas = new javax.swing.JTable();
        lArtConTabla = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtArtCompras = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtArtConsultas = new javax.swing.JTable();
        lArtVentas = new javax.swing.JLabel();
        lArtCompras = new javax.swing.JLabel();
        lArtCate = new javax.swing.JLabel();
        cbArtCate = new javax.swing.JComboBox<>();
        lArtSubcate = new javax.swing.JLabel();
        cbArtSubcate = new javax.swing.JComboBox<>();
        bArtBuscar = new javax.swing.JButton();
        pStocks = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO");

        pPrincipal.setLayout(new java.awt.CardLayout());

        pLogin.setBackground(new java.awt.Color(204, 255, 255));

        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMiniLoginLayout = new javax.swing.GroupLayout(pMiniLogin);
        pMiniLogin.setLayout(pMiniLoginLayout);
        pMiniLoginLayout.setHorizontalGroup(
            pMiniLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMiniLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pMiniLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(tfPass)
                    .addComponent(tfUsuario))
                .addGap(28, 28, 28))
        );
        pMiniLoginLayout.setVerticalGroup(
            pMiniLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMiniLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tfUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPass)
                .addGap(28, 28, 28)
                .addComponent(bEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(pMiniLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(pMiniLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(277, 277, 277))
        );

        pPrincipal.add(pLogin, "card5");

        bFrances.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/france.png"))); // NOI18N
        bFrances.setToolTipText("Francés");
        bFrances.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/francehover.png"))); // NOI18N
        bFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFrancesActionPerformed(evt);
            }
        });

        bIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/UK.png"))); // NOI18N
        bIngles.setToolTipText("Inglés");
        bIngles.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/UKhover.png"))); // NOI18N
        bIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInglesActionPerformed(evt);
            }
        });

        bEspanhol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/spain.png"))); // NOI18N
        bEspanhol.setToolTipText("Español");
        bEspanhol.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/spainhover.png"))); // NOI18N
        bEspanhol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEspanholActionPerformed(evt);
            }
        });

        lpUsuario.setLayer(etiqNA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpUsuario.setLayer(etiqUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpUsuario.setLayer(bFrances, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpUsuario.setLayer(bIngles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpUsuario.setLayer(bEspanhol, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpUsuarioLayout = new javax.swing.GroupLayout(lpUsuario);
        lpUsuario.setLayout(lpUsuarioLayout);
        lpUsuarioLayout.setHorizontalGroup(
            lpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(etiqUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(etiqNA, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEspanhol, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bFrances, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        lpUsuarioLayout.setVerticalGroup(
            lpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpUsuarioLayout.createSequentialGroup()
                .addGroup(lpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiqUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(etiqNA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(lpUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bFrances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEspanhol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bIngles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bMenuCompras.setBackground(new java.awt.Color(255, 255, 255));
        bMenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/compra.png"))); // NOI18N
        bMenuCompras.setToolTipText("Compras");
        bMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuComprasActionPerformed(evt);
            }
        });

        bMenuVentas.setBackground(new java.awt.Color(255, 255, 255));
        bMenuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/venta.png"))); // NOI18N
        bMenuVentas.setToolTipText("Ventas");
        bMenuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuVentasActionPerformed(evt);
            }
        });

        bMenuUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        bMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/user.png"))); // NOI18N
        bMenuUsuarios.setToolTipText("Usuarios");
        bMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuUsuariosActionPerformed(evt);
            }
        });

        bSalir.setBackground(new java.awt.Color(255, 255, 255));
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit.gif"))); // NOI18N
        bSalir.setToolTipText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bMenuArticulos.setBackground(new java.awt.Color(255, 255, 255));
        bMenuArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/objects.png"))); // NOI18N
        bMenuArticulos.setToolTipText("Artículos");
        bMenuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuArticulosActionPerformed(evt);
            }
        });

        bMenuClientes1.setBackground(new java.awt.Color(255, 255, 255));
        bMenuClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clientes.png"))); // NOI18N
        bMenuClientes1.setToolTipText("Clientes");
        bMenuClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuClientes1ActionPerformed(evt);
            }
        });

        bMenuAjustes.setBackground(new java.awt.Color(255, 255, 255));
        bMenuAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AJUSTES.png"))); // NOI18N
        bMenuAjustes.setToolTipText("Ajustes");
        bMenuAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuAjustesActionPerformed(evt);
            }
        });

        lpMenus.setLayer(bMenuCompras, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bMenuVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bMenuUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bMenuArticulos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bMenuClientes1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpMenus.setLayer(bMenuAjustes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpMenusLayout = new javax.swing.GroupLayout(lpMenus);
        lpMenus.setLayout(lpMenusLayout);
        lpMenusLayout.setHorizontalGroup(
            lpMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpMenusLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bMenuUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMenuArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMenuCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMenuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bMenuClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(bMenuAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267)
                .addComponent(bSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        lpMenusLayout.setVerticalGroup(
            lpMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpMenusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuClientes1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bMenuAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pMenusillo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pRegistrarCompraLayout = new javax.swing.GroupLayout(pRegistrarCompra);
        pRegistrarCompra.setLayout(pRegistrarCompraLayout);
        pRegistrarCompraLayout.setHorizontalGroup(
            pRegistrarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        pRegistrarCompraLayout.setVerticalGroup(
            pRegistrarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpCompras.addTab("Registrar Compra", pRegistrarCompra);

        pMenusillo.add(tpCompras, "card4");

        javax.swing.GroupLayout pRegistrarVentaLayout = new javax.swing.GroupLayout(pRegistrarVenta);
        pRegistrarVenta.setLayout(pRegistrarVentaLayout);
        pRegistrarVentaLayout.setHorizontalGroup(
            pRegistrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        pRegistrarVentaLayout.setVerticalGroup(
            pRegistrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpVentas.addTab("Registar Venta", pRegistrarVenta);

        pMenusillo.add(tpVentas, "card5");

        javax.swing.GroupLayout pPreferenciasLayout = new javax.swing.GroupLayout(pPreferencias);
        pPreferencias.setLayout(pPreferenciasLayout);
        pPreferenciasLayout.setHorizontalGroup(
            pPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        pPreferenciasLayout.setVerticalGroup(
            pPreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpAjustes.addTab("Preferencias", pPreferencias);

        pMenusillo.add(tpAjustes, "card6");

        pConsultaUsuarios.setBackground(new java.awt.Color(204, 204, 204));

        jtGeneralUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtGeneralUsuarios.getTableHeader().setReorderingAllowed(false);
        jtGeneralUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGeneralUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtGeneralUsuarios);

        jtUsuariosTiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtUsuariosTiendas);

        lTrabajadores.setText("Trabajadores");

        lTiendas.setText("Tiendas");

        jtUsuariosAcceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jtUsuariosAcceso);

        lUsuarioAcceso.setText("Usuario de Acceso");

        lUsuID.setText("jLabel1");

        lUsuNombre.setText("jLabel1");

        lUsuDNI.setText("jLabel1");

        lUsuFecha.setText("jLabel1");

        lUsuApe2.setText("jLabel1");

        lUsuDireccion.setText("jLabel1");

        lUsuSexo.setText("jLabel1");

        lUsuApe1.setText("jLabel1");

        lUsuTelefono.setText("jLabel1");

        lFoto.setText("jLabel1");

        bUsuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/images.png"))); // NOI18N

        bUsuLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpiar.jpg"))); // NOI18N

        bUsuActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/actu.png"))); // NOI18N

        javax.swing.GroupLayout pConsultaUsuariosLayout = new javax.swing.GroupLayout(pConsultaUsuarios);
        pConsultaUsuarios.setLayout(pConsultaUsuariosLayout);
        pConsultaUsuariosLayout.setHorizontalGroup(
            pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                .addComponent(lUsuNombre)
                                .addGap(18, 18, 18)
                                .addComponent(tfUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lTrabajadores)
                                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                        .addComponent(lUsuID)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfUsuID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pConsultaUsuariosLayout.createSequentialGroup()
                                                .addComponent(lUsuApe1)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfUsuApe1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lUsuApe2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pConsultaUsuariosLayout.createSequentialGroup()
                                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pConsultaUsuariosLayout.createSequentialGroup()
                                                        .addComponent(lUsuFecha)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tfUsuFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                                        .addComponent(lUsuDNI)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tfUsuDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(69, 69, 69)))
                                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lUsuDireccion)
                                                    .addComponent(lUsuTelefono))))
                                        .addGap(38, 38, 38)
                                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfUsuDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfUsuApe2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                                .addComponent(tfUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lUsuSexo)))))
                                .addGap(41, 41, 41))))
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lTiendas)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lUsuarioAcceso)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaUsuariosLayout.createSequentialGroup()
                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfUsuSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lFoto)
                                        .addGap(78, 78, 78))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaUsuariosLayout.createSequentialGroup()
                                        .addComponent(lFotoIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)))
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bUsuConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bUsuLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bUsuActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(207, 207, 207))))
        );
        pConsultaUsuariosLayout.setVerticalGroup(
            pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lFotoIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bUsuConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUsuLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bUsuActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lUsuID)
                                    .addComponent(tfUsuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lUsuNombre)
                                    .addComponent(tfUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lUsuApe1)
                                    .addComponent(tfUsuApe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUsuApe2))
                                .addGap(17, 17, 17)
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lUsuDNI)
                                    .addComponent(tfUsuDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultaUsuariosLayout.createSequentialGroup()
                                .addComponent(tfUsuApe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfUsuDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lUsuDireccion))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lUsuFecha)
                    .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfUsuFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lUsuTelefono)
                        .addComponent(tfUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lUsuSexo)
                        .addComponent(tfUsuSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTiendas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTrabajadores))
                .addGap(18, 18, 18)
                .addGroup(pConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultaUsuariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(85, 85, 85)
                        .addComponent(lUsuarioAcceso)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        tpUsuarios.addTab("Consulta Usuarios", pConsultaUsuarios);

        jtPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtPruebas);

        javax.swing.GroupLayout pInsertaUsuariosLayout = new javax.swing.GroupLayout(pInsertaUsuarios);
        pInsertaUsuarios.setLayout(pInsertaUsuariosLayout);
        pInsertaUsuariosLayout.setHorizontalGroup(
            pInsertaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInsertaUsuariosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        pInsertaUsuariosLayout.setVerticalGroup(
            pInsertaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInsertaUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        tpUsuarios.addTab("Creación de Usuarios", pInsertaUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpUsuarios.addTab("tab3", jPanel3);

        pMenusillo.add(tpUsuarios, "card2");

        lArtReferencia.setText("Referencia");

        jtArtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtArtVentas);

        lArtConTabla.setText("Referencias");

        jtArtCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jtArtCompras);

        jtArtConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jtArtConsultas);

        lArtVentas.setText("Ventas");

        lArtCompras.setText("Compras");

        lArtCate.setText("Categoría");

        lArtSubcate.setText("Subcategoría");

        javax.swing.GroupLayout pConsultasArticulosLayout = new javax.swing.GroupLayout(pConsultasArticulos);
        pConsultasArticulos.setLayout(pConsultasArticulosLayout);
        pConsultasArticulosLayout.setHorizontalGroup(
            pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultasArticulosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lArtConTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 580, Short.MAX_VALUE)
                .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lArtCompras)
                    .addComponent(lArtVentas)
                    .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lArtReferencia)
                .addGap(18, 18, 18)
                .addComponent(tfArtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lArtCate)
                .addGap(54, 54, 54)
                .addComponent(cbArtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lArtSubcate)
                .addGap(51, 51, 51)
                .addComponent(cbArtSubcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bArtBuscar)
                .addGap(95, 95, 95))
            .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(613, Short.MAX_VALUE)))
        );
        pConsultasArticulosLayout.setVerticalGroup(
            pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lArtReferencia)
                    .addComponent(tfArtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lArtCate)
                    .addComponent(cbArtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lArtSubcate)
                    .addComponent(cbArtSubcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bArtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lArtVentas)
                .addGap(18, 18, 18)
                .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                        .addComponent(lArtConTabla)
                        .addGap(154, 154, 154)
                        .addComponent(lArtCompras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(pConsultasArticulosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pConsultasArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsultasArticulosLayout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        tpArticulos.addTab("Consultas", pConsultasArticulos);

        javax.swing.GroupLayout pStocksLayout = new javax.swing.GroupLayout(pStocks);
        pStocks.setLayout(pStocksLayout);
        pStocksLayout.setHorizontalGroup(
            pStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
        pStocksLayout.setVerticalGroup(
            pStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        tpArticulos.addTab("Stocks", pStocks);

        pMenusillo.add(tpArticulos, "card6");

        javax.swing.GroupLayout pAppLayout = new javax.swing.GroupLayout(pApp);
        pApp.setLayout(pAppLayout);
        pAppLayout.setHorizontalGroup(
            pAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAppLayout.createSequentialGroup()
                .addGroup(pAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lpUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lpMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pAppLayout.createSequentialGroup()
                    .addComponent(pMenusillo, javax.swing.GroupLayout.PREFERRED_SIZE, 896, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pAppLayout.setVerticalGroup(
            pAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAppLayout.createSequentialGroup()
                .addComponent(lpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lpMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(566, Short.MAX_VALUE))
            .addGroup(pAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAppLayout.createSequentialGroup()
                    .addGap(0, 185, Short.MAX_VALUE)
                    .addComponent(pMenusillo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pPrincipal.add(pApp, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        List<String> valores = new ArrayList<>();

      /*  String[] vUsario = new String[5];
        valores = loguearse(tfUsuario.getText(), tfPass.getText());
        valores.toArray(vUsario);
        if (vUsario[0] == null) {
            JOptionPane.showMessageDialog(null, "Usuario Incorrecto");
        } else {

            Global.id_usuario = Integer.parseInt(vUsario[0]);
            Global.id_nivel_acceso = Integer.parseInt(vUsario[3]);
            etiqUsuario.setText(vUsario[1] + " " + vUsario[2]);
            etiqNA.setText(vUsario[4]);

            mostrar_menus();

        }*/
mostrar_menus();
    }//GEN-LAST:event_bEntrarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuUsuariosActionPerformed

        pMenusillo.setVisible(true);
        cartaMenus.show(pMenusillo, "tpUsuarios");
        rellenaUsuariosGeneral();


    }//GEN-LAST:event_bMenuUsuariosActionPerformed

    private void jtGeneralUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGeneralUsuariosMouseClicked

        //eliminar lo que haya
        int row = jtGeneralUsuarios.getSelectedRow();
        id_trabajador = Integer.parseInt(String.valueOf(jtGeneralUsuarios.getValueAt(row, 0)));
        Tablas.rellenaTablaUsuariosLogueo(id_trabajador);
        Tablas.rellenaTablaUsuariosTiendas(id_trabajador);


    }//GEN-LAST:event_jtGeneralUsuariosMouseClicked

    private void bMenuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuArticulosActionPerformed

        pMenusillo.setVisible(true);
        cartaMenus.show(pMenusillo, "tpArticulos");
        Combos.comboArtCategorias();


    }//GEN-LAST:event_bMenuArticulosActionPerformed

    private void bMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuComprasActionPerformed

        pMenusillo.setVisible(true);
        cartaMenus.show(pMenusillo, "tpCompras");


    }//GEN-LAST:event_bMenuComprasActionPerformed

    private void bMenuClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuClientes1ActionPerformed

      

    }//GEN-LAST:event_bMenuClientes1ActionPerformed

    private void bMenuAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuAjustesActionPerformed

        pMenusillo.setVisible(true);
        cartaMenus.show(pMenusillo, "tpAjustes");


    }//GEN-LAST:event_bMenuAjustesActionPerformed

    private void bInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInglesActionPerformed
        Idiomas.Ingles.cambiarAIngles();
    }//GEN-LAST:event_bInglesActionPerformed

    private void bFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFrancesActionPerformed
        Idiomas.Frances.cambiarAFrances();
    }//GEN-LAST:event_bFrancesActionPerformed

    private void bEspanholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEspanholActionPerformed
      Idiomas.Espanhol.cambiarAEspanhol();
    }//GEN-LAST:event_bEspanholActionPerformed

    private void bMenuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuVentasActionPerformed
      
          pMenusillo.setVisible(true);
        cartaMenus.show(pMenusillo, "tpVentas");

        
        
    }//GEN-LAST:event_bMenuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton bArtBuscar;
    private javax.swing.JButton bEntrar;
    public static javax.swing.JButton bEspanhol;
    public static javax.swing.JButton bFrances;
    public static javax.swing.JButton bIngles;
    public static javax.swing.JButton bMenuAjustes;
    public static javax.swing.JButton bMenuArticulos;
    public static javax.swing.JButton bMenuClientes1;
    public static javax.swing.JButton bMenuCompras;
    public static javax.swing.JButton bMenuUsuarios;
    public static javax.swing.JButton bMenuVentas;
    public static javax.swing.JButton bSalir;
    public static javax.swing.JButton bUsuActualizar;
    public static javax.swing.JButton bUsuConsultar;
    public static javax.swing.JButton bUsuLimpiar;
    public static javax.swing.JComboBox<String> cbArtCate;
    public static javax.swing.JComboBox<String> cbArtSubcate;
    protected static javax.swing.JLabel etiqNA;
    protected static javax.swing.JLabel etiqUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jtArtCompras;
    public static javax.swing.JTable jtArtConsultas;
    public static javax.swing.JTable jtArtVentas;
    public static javax.swing.JTable jtGeneralUsuarios;
    public static javax.swing.JTable jtPruebas;
    public static javax.swing.JTable jtUsuariosAcceso;
    public static javax.swing.JTable jtUsuariosTiendas;
    public static javax.swing.JLabel lArtCate;
    public static javax.swing.JLabel lArtCompras;
    public static javax.swing.JLabel lArtConTabla;
    public static javax.swing.JLabel lArtReferencia;
    public static javax.swing.JLabel lArtSubcate;
    public static javax.swing.JLabel lArtVentas;
    public static javax.swing.JLabel lFoto;
    private javax.swing.JLabel lFotoIMG;
    public static javax.swing.JLabel lTiendas;
    public static javax.swing.JLabel lTrabajadores;
    public static javax.swing.JLabel lUsuApe1;
    public static javax.swing.JLabel lUsuApe2;
    public static javax.swing.JLabel lUsuDNI;
    public static javax.swing.JLabel lUsuDireccion;
    public static javax.swing.JLabel lUsuFecha;
    public static javax.swing.JLabel lUsuID;
    public static javax.swing.JLabel lUsuNombre;
    public static javax.swing.JLabel lUsuSexo;
    public static javax.swing.JLabel lUsuTelefono;
    public static javax.swing.JLabel lUsuarioAcceso;
    private static javax.swing.JLayeredPane lpMenus;
    private static javax.swing.JLayeredPane lpUsuario;
    private static javax.swing.JPanel pApp;
    public static javax.swing.JPanel pConsultaUsuarios;
    private javax.swing.JPanel pConsultasArticulos;
    public static javax.swing.JPanel pInsertaUsuarios;
    private static javax.swing.JPanel pLogin;
    public static javax.swing.JPanel pMenusillo;
    private javax.swing.JPanel pMiniLogin;
    private javax.swing.JPanel pPreferencias;
    private static javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pRegistrarCompra;
    private javax.swing.JPanel pRegistrarVenta;
    private javax.swing.JPanel pStocks;
    private javax.swing.JTextField tfArtReferencia;
    private javax.swing.JTextField tfPass;
    public static javax.swing.JTextField tfUsuApe1;
    public static javax.swing.JTextField tfUsuApe2;
    public static javax.swing.JTextField tfUsuDNI;
    public static javax.swing.JTextField tfUsuDireccion;
    public static javax.swing.JTextField tfUsuFecha;
    public static javax.swing.JTextField tfUsuID;
    public static javax.swing.JTextField tfUsuNombre;
    public static javax.swing.JTextField tfUsuSexo;
    public static javax.swing.JTextField tfUsuTelefono;
    private javax.swing.JTextField tfUsuario;
    public static javax.swing.JTabbedPane tpAjustes;
    public static javax.swing.JTabbedPane tpArticulos;
    public static javax.swing.JTabbedPane tpCompras;
    public static javax.swing.JTabbedPane tpUsuarios;
    public static javax.swing.JTabbedPane tpVentas;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> loguearse(java.lang.String arg0, java.lang.String arg1) {
        servicio_usuarios.Usuarios_Service service = new servicio_usuarios.Usuarios_Service();
        servicio_usuarios.Usuarios port = service.getUsuariosPort();
        return port.loguearse(arg0, arg1);
    }

}
